codp1, npeca1, vunitario1 = input().split()
codp2, npeca2, vunitario2 = input().split()
codp1 = int(codp1)
npeca1 = int(npeca1)
vunitario1 = float(vunitario1)
codp2 = int(codp2)
npeca2 = int(npeca2)
vunitario2 = float(vunitario2)
vpagar = (npeca1 * vunitario1) + (npeca2 * vunitario2)
print("VALOR A PAGAR: R$ {:.2f}".format(vpagar))
